### ISSUE TITLE
Find resource leak

### ISSUE THREAD

**Issue by gatepoet** [statisticsnorway/statbus#17]
If this still exists

**Comment by AnneAbelseth** [comment]
Once in Morocco we were installing on a linux machine (not wsl2 - a virtual ubuntu). After working on the system for a few days - the disks suddenly was filled up to such a degree that we couldn't even delete files to fix it: Every partition was 100% full.

I have not been able to re-create this problem later, and I don't know whether it is still there, but we should be on lookout for it..

**Comment by jhf** [comment]
This is no longer relevant with the revamped source code, and a new ticket will need to be made if the same problem occurs with the revamped code.
